name: Keep Render Services Awake

on:
  schedule:
    - cron: "*/10 * * * *" # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Show current time
        run: echo "Cron job running at $(date)"

      - name: Send HEAD requests asynchronously and log response time & status
        run: |
          echo "Waking up Render services..."

          # Run API calls asynchronously and capture response time + status code
          {
            echo "[Auth Service] $(curl -o /dev/null -s -w "Time: %{time_total}s | Status: %{http_code}\n" https://sharelink-auth.onrender.com/health)"
          } & 

          {
            echo "[Campaigns Service] $(curl -o /dev/null -s -w "Time: %{time_total}s | Status: %{http_code}\n" https://sharelink-campaigns.onrender.com/health)"
          } & 

          {
            echo "[Integrations Service] $(curl -o /dev/null -s -w "Time: %{time_total}s | Status: %{http_code}\n" https://sharelink-integrations.onrender.com/health)"
          } & 

          {
            echo "[Notifications Service] $(curl -o /dev/null -s -w "Time: %{time_total}s | Status: %{http_code}\n" https://sharelink-notifications.onrender.com/health)"
          } & 

          {
            echo "[Wallet Service] $(curl -o /dev/null -s -w "Time: %{time_total}s | Status: %{http_code}\n" https://sharelink-wallet.onrender.com/health)"
          } & 

          # Wait for all background processes to finish
          wait

          echo "All API calls completed!"
